@startuml
[*] --> Idle
Idle --> Read : TAP_READ & !TAP_WRITE
Idle --> Write : !TAP_READ & TAP_WRITE
Read --> WaitACK
Write --> ReadDMI : op=op_read
Write --> WriteDMI: op=op_write
Write --> WaitACK : op=op_nop
ReadDMI --> WaitReadDMI : dmi_req_ready
ReadDMI : dmi_req_valid = 1
WaitReadDMI --> WaitACK : dmi_resp_valid
WriteDMI --> WaitWriteDMI : dmi_req_ready
WriteDMI : dmi_req_valid = 1
WaitWriteDMI --> WaitACK : dmi_resp_valid
WaitACK --> Idle : !TAP_READ & !TAP_Write
WaitACK : done = 1
@enduml
