@startuml
ditaa
UART_TAP
                +------------+      +---------+ RE        +-------------+
dmi_read_valid  | DMI Handler|      | TAP FSM |---------->|  UART       | RX
--------------->|            | Read |         | WE        |             |<----
dmi_read_ready  |            |<-----|         |---------->|             |
<---------------|            | Write|         | TX_READY  |             |
dmi_read        |            |<-----|         |---------->|             |
--------------->|            |DMI_I |         | RX_EMPTY  |             |
                |            |<-----|         |---------->|             |
                |            |DMI_O |         | DSEND     |             | TX
dmi_write_valid |            |----->|         |---------->|             |--->
<---------------|            |Done  |         | DREC      |             |
dmi_write_ready |            |----->|         |---------->|             |
--------------->|            |      |         |           +-------------+
dmi_write       |            |      |         |
<---------------|            |      |         | D_I       +-------------+
                |            |      |         |---------->|De/Serializer|
                |            |      |         | REG_O     |    DMI      |
                |            |      |         |<----------|             |
                |            |      |         | D_O       |             |
                |            |      |         |---------->|             |
                |            |      |         | REG_I     |             |
                |            |      |         |<----------|             |
                |            |      |         | Run       |             |
                |            |      |         |---------->|             |
                |            |      |         | Done      |             |
                |            |      |         |<----------+-------------+
                +------------+      +---------+
@enduml
