@startuml

[*] --> Idle
Idle --> Header
Header --> CmdAddr : !RX_EMPTY &\n DREC = HEADER
CmdAddr --> Length : !RX_EMPTY
Length --> Write : CMD_WRITE
Length --> Read : CMD_READ
Length --> RW : CMD_RW
Length --> Reset : CMD_RESET
Write --> Idle : SER_DONE &\n DMI_DONE |\n MSG_TIMEOUT
Read --> Idle : SER_DONE &\n DMI_DONE |\n MSG_TIMEOUT
RW --> Idle : SER_DONE &\n DMI_DONE |\n MSG_TIMEOUT

Reset --> Idle
@enduml
